# Generated by Django 5.1.4 on 2024-12-19 11:36

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('description', models.TextField()),
                ('steps_cooking', models.TextField()),
                ('time_for_cooking', models.IntegerField(default=10)),
            ],
        ),
    ]
